apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  namespace: devops-observability
  labels:
    app: tempo
    component: observability
spec:
  selector:
    app: tempo
  ports:
  - name: http
    port: 3200
    targetPort: 3200
    protocol: TCP
  - name: grpc
    port: 9095
    targetPort: 9095
    protocol: TCP
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  - name: memberlist
    port: 7946
    targetPort: 7946
    protocol: TCP
