apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: fullcycle-api
  newName: slmakomazi/fullcycle-api
  newTag: v1.17

configMapGenerator:
- name: fullcycle-config-local
  literals:
  - LOG_LEVEL=DEBUG
  - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,prometheus

patches:
- path: deployment-patch.yaml
