apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: fullcycle-api
  newName: slmakomazi/fullcycle-api
  newTag: v1.11

patches:
- path: deployment-patch.yaml
