{{- if .Values.persistentVolumeClaims.logs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "devops-observability-api.fullname" . }}-logs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devops-observability-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: logs
  {{- with .Values.persistentVolumeClaims.logs.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistentVolumeClaims.logs.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistentVolumeClaims.logs.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaims.logs.size }}
{{- end }}
