pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = 'slmakomazi/fullcycle-api'
        DOCKER_TAG = 'latest'
        DOCKERFILE_PATH = './api/Dockerfile'
        BUILD_CONTEXT = './api'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/SLMakomazi/FullCycleDevOps.git', changelog: false
            }
        }
        
        stage('Maven Build') {
            steps {
                dir('api') {
                    sh 'mvn clean compile'
                }
            }
        }
        
        stage('Maven Test') {
            steps {
                dir('api') {
                    sh 'mvn test -Dsurefire.useFile=true -Dmaven.test.failure.ignore=false'
                }
                script {
                    if (fileExists('api/target/surefire-reports')) {
                        junit 'api/target/surefire-reports/*.xml'
                    } else {
                        echo "No test reports found - skipping JUnit publish"
                    }
                }
            }
        }
        
        stage('Docker Build') {
            steps {
                script {
                    def customImage = docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}", "${BUILD_CONTEXT} -f ${DOCKERFILE_PATH}")
                    docker.withRegistry('', 'docker-hub-credentials') {
                        customImage.push()
                    }
                }
            }
        }
        
        stage('Docker Tag Latest') {
            steps {
                script {
                    def customImage = docker.image("${DOCKER_IMAGE}:latest")
                    docker.withRegistry('', 'docker-hub-credentials') {
                        customImage.push('latest')
                    }
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
            echo "Pipeline finished"
        }
    }
}
