version: '3.8'

services:
  api:
    image: slmakomazi/fullcycle-api:v1
    container_name: devops-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/devops
    depends_on:
      - mongodb
    networks:
      - devops-network

  mongodb:
    image: mongo:6
    container_name: devops-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - devops-network

volumes:
  mongo-data:

networks:
  devops-network:
    driver: bridge
